name: Build Toolchain

on:
  workflow_dispatch:
  push:
    branches: [main]


permissions:
  contents: write

jobs:
  build:
    name: Build (x86_64, host ${{ matrix.host }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: x86_64-linux
            os: ubuntu-latest
          - host: arm64-darwin
            os: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential libgmp-dev libmpfr-dev libmpc-dev texinfo curl xz-utils meson ninja-build git python3 autoconf xorriso

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gmp mpfr libmpc texinfo xz meson ninja python3 autoconf xorriso
          echo "/opt/homebrew/opt/texinfo/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/texinfo/bin" >> $GITHUB_PATH

      - name: Build toolchain
        run: |
          chmod +x workflow.sh
          ./workflow.sh "${{ github.workspace }}/ethereal-toolchain" "x86_64"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ethereal-x86_64-toolchain-${{ matrix.host }}
          path: ethereal-*-toolchain.tar.xz
