name: Build Toolchain

on:
  workflow_dispatch:
  push:
    branches: [main]


permissions:
  contents: write

jobs:
  build:
    name: Build (x86_64, host ${{ matrix.host }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: x86_64-linux
            os: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential libgmp-dev libmpfr-dev libmpc-dev texinfo curl xz-utils meson ninja-build git python3 autoconf xorriso

      - name: Build toolchain
        run: |
          chmod +x workflow.sh
          ./workflow.sh "${{ github.workspace }}/ethereal-toolchain" "x86_64"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ethereal-x86_64-toolchain-${{ matrix.host }}
          path: ethereal-*-toolchain.tar.xz

      - name: Upload error logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: libgcc-error-log
          path: ${{ github.workspace }}/build-gcc/x86_64-ethereal/libgcc/config.log
        
